version: '3.8'

services:

  dynamodb:
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb
    networks:
      - scylla
    expose:
      - 8001
    ports:
      - "8001:8000"
    working_dir: /home/dynamodblocal

  cassandra:
    image: cassandra:latest
    networks:
      - scylla
    volumes:
      - ./tests/docker/cassandra:/var/lib/cassandra
    ports:
      - "9043:9042"
    expose:
      - 9043

  scylla-source:
    image: scylladb/scylla:latest
    networks:
      - scylla
    volumes:
      - "./tests/docker/scylla-source:/var/lib/scylla"
    ports:
      - "8002:8000"
      - "9044:9042"
    expose:
      - 9044
    command: "--smp 1 --memory 2048M --alternator-port 8000 --alternator-write-isolation only_rmw_uses_lwt"

  scylla:
    image: scylladb/scylla:latest
    networks:
      - scylla
    volumes:
      - "./tests/docker/scylla:/var/lib/scylla"
    ports:
      - "8000:8000"
      - "9042:9042"
    command: "--smp 1 --memory 2048M --alternator-port 8000 --alternator-write-isolation only_rmw_uses_lwt"

  s3:
    image: localstack/localstack:s3-latest
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
    environment:
      - DEBUG=${DEBUG:-0}
    volumes:
      - "./tests/docker/s3:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - scylla

  spark-master:
    image: bde2020/spark-master:3.0.2-hadoop3.2
    container_name: spark-master
    hostname: spark-master
    environment:
      INIT_DAEMON_STEP: setup_spark
      SPARK_MASTER: spark://spark-master:7077
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: spark-master
    networks:
      - scylla
    expose:
      - 5005
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7006
      - 7077
      - 6066
    ports:
      - 4040:4040
      - 5005:5005
      - 6066:6066
      - 7077:7077
      - 8080:8080
    volumes:
      - ./migrator/target/scala-2.12:/jars
      - ./tests/src/test/configurations:/app/configurations
      - ./tests/docker/spark-master:/app/savepoints
      - ./tests/docker/parquet:/app/parquet
      # Workaround for https://github.com/awslabs/emr-dynamodb-connector/issues/50
      - ${PWD}/tests/docker/job-flow.json:/mnt/var/lib/info/job-flow.json

  spark-worker:
    image: bde2020/spark-worker:3.0.2-hadoop3.2
    hostname: spark-worker
    container_name: spark-worker-1
    environment:
      SPARK_WORKER_CORES: 3
      SPARK_WORKER_MEMORY: 1024m
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_PUBLIC_DNS: spark-worker
    networks:
      - scylla
    expose:
      - 5006
      - 7012
      - 7013
      - 7014
      - 7015
      - 7016
    ports:
      - 5006:5006
      - 8081:8081
    volumes:
      - ./tests/docker/parquet:/app/parquet
    depends_on:
      - spark-master

networks:
  scylla:
